services:
  - type: web
    name: bank-app
    runtime: docker
    plan: free
    rootDir: back
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false